steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - GIT_SHA=${_GIT_SHA}
      - --tag
      - ${_IMAGE_URI}
      - .
images:
  - ${_IMAGE_URI}
options:
  logging: CLOUD_LOGGING_ONLY
